# This file was autogenerated from running 'tests/async.py'.

from aaa1111 import AAA1111


class TestAction:
    api = AAA1111(username="aaa1111", password="test")

    async def test_refresh_checkpoints(self):
        await self.api.arefresh_checkpoints()

    async def test_unload_checkpoint(self):
        await self.api.aunload_checkpoint()

    async def test_reload_checkpoint(self):
        await self.api.areload_checkpoint()
